version: "3"

services:
  database:
    container_name: medievalstore_database
    build: ./database
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./backend/database/db:/docker-entrypoint-initdb.d

  api:
    build: '.'
    container_name: medievalstore_compose
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - database
    ports:
      - 3001:3001
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: database
